apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nginx-proxy-manager.fullname" . }}-data
  namespace: {{ .Values.namespace | default "npm" }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.data.size | default "5Gi" }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nginx-proxy-manager.fullname" . }}-letsencrypt
  namespace: {{ .Values.namespace | default "npm" }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.letsencrypt.size | default "1Gi" }}
