apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-proxy-manager.fullname" . }}-proxy
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.proxy.type }}
  externalTrafficPolicy: {{ .Values.service.proxy.externalTrafficPolicy }}
  ports: {{ toYaml .Values.service.proxy.ports | nindent 2 }}
  selector:
    app: {{ include "nginx-proxy-manager.name" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-proxy-manager.fullname" . }}-admin-ui
  namespace: {{ .Values.namespace }}
spec:
  ports: {{ toYaml .Values.service.adminUI.ports | nindent 2 }}
  selector:
    app: {{ include "nginx-proxy-manager.name" . }}
