apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-proxy-manager.fullname" . }}-proxy
  namespace: {{ .Values.namespace | default "npm" }}
spec:
  ports:
    - name: proxy
      port: 80
      protocol: TCP
      targetPort: 80
    - name: proxy-ssl
      port: 443
      protocol: TCP
      targetPort: 443
  selector:
    app: {{ include "nginx-proxy-manager.name" . }}
  externalTrafficPolicy: Local
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-proxy-manager.fullname" . }}-admin-ui
  namespace: {{ .Values.namespace | default "npm" }}
spec:
  ports:
    - name: admin-ui
      port: 81
      protocol: TCP
      targetPort: 81
  selector:
    app: {{ include "nginx-proxy-manager.name" . }}
