# Default values for nginx-proxy-manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: jc21/nginx-proxy-manager
  pullPolicy: IfNotPresent
  tag: latest

namespace: npm

service:
  proxy:
    type: LoadBalancer
    externalTrafficPolicy: Local
    ports:
      - name: proxy
        port: 80
        targetPort: 80
      - name: proxy-ssl
        port: 443
        targetPort: 443
  adminUI:
    ports:
      - name: admin-ui
        port: 81
        targetPort: 81

pvc:
  data:
    size: 5Gi
  letsencrypt:
    size: 1Gi

serviceAccount:
  create: true
  name: ""
  annotations: {}

autoscaling:
  enabled: false

ingress:
  enabled: false

